artist:
  name: Yes M.A.M. Music
  tagline: Middle Aged Men (M.A.M.)
  seo_title: Yes M.A.M. Music
  # seo_description:
  # contact_twitter_username: gshaddixmusic
  # contact_phone: 
  # contact_email: cosmiccowboymedia@gmail.com

social:
  - name: Facebook
    url: https://www.facebook.com/yesmam2017
  - name: Instagram
    url: https://www.instagram.com/yesmammusic/
  - name: Youtube
    url: https://www.youtube.com/channel/UCilRD3yW4Su2jhZItxb6D_Q
  - name: Spotify
    url: https://open.spotify.com/artist/7pPuS77gOHBTDbVTIyH1th
  - name: Apple
    url: https://music.apple.com/us/artist/yes-m-a-m/1468009142

site_language: en
